parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: bell
    database_user: ec2
    database_password: stock99915
    charset: UTF8
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d9d3db754790de17c8d0cce65556df94b8adc5c0
